# Generated by Django 2.2 on 2023-11-30 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('labs', '0002_investigations_specimens_wards'),
    ]

    operations = [
        migrations.CreateModel(
            name='Records',
            fields=[
                ('record_id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('date', models.DateTimeField(auto_now=True)),
                ('receipt_num', models.IntegerField(blank=True, null=True, unique=True)),
                ('patient_name', models.CharField(max_length=400)),
                ('hospital_num', models.CharField(max_length=50)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('sex', models.CharField(max_length=10)),
                ('cost', models.DecimalField(decimal_places=1, default=0.0, max_digits=15)),
                ('investigation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='investigations', to='labs.Investigations')),
                ('specimen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='specimens', to='labs.Specimens')),
                ('ward', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wards', to='labs.Wards')),
            ],
        ),
    ]
